root: ./

​structure:
  readme: README.md
  summary: SUMMARY.md​

redirects:
  system/architecture.md: README.md
  technology/v3.md: technology/deployments
  technology/makers.md: technology/servers
  technology/request-for-quote: technology/protocols
  technology/last-look.md: technology/protocols