root: ./

​structure:
  readme: README.md
  summary: SUMMARY.md​

redirects:
  system/architecture.md: README.md
  technology/v3.md: technology/deployments.md
  technology/makers.md: technology/servers.md
  technology/request-for-quote.md: technology/protocols.md
  technology/last-look.md: technology/protocols.md