root: ./

​structure:
  readme: README.md
  summary: SUMMARY.md​

redirects:
  instant/contract-deployments: system/contract-deployments.md
  instant/add-to-your-app: guides/embed-airswap.md
  trader/add-to-your-app: guides/embed-airswap.md
